targets:
  $default:
    builders:
      stacked_generator|stackedLocatorGenerator:
        enabled: true
        generate_for:
          exclude:
            - test
            - .dart_tool
          include:
            - test/integration/*
            - test/integration/**/*
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  # Generate the router file and routes
  stackedRouterGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedRouterGenerator"]
    build_extensions: { ".dart": [".router.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the stacked locator service registrations
  stackedLocatorGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedLocatorGenerator"]
    build_extensions: { ".dart": [".locator.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the form view
  stackedFormGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedFormGenerator"]
    build_extensions: { ".dart": [".form.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the logger
  stackedLoggerGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedLoggerGenerator"]
    build_extensions: { ".dart": [".logger.dart"] }
    auto_apply: dependents
    build_to: source
