targets:
  $default:
    builders:
      stacked_generator|stackedLocatorGenerator:
        enabled: true
        generate_for:
          exclude:
            - test
            - .dart_tool
          include:
            - test/getit/integration_test/samples/*
            - test/getit/integration_test/samples/**
      stacked_generator|stackedLoggerGenerator:
        enabled: true
        generate_for:
          exclude:
            - test
            - .dart_tool
          include:
            - test/logging/integration_test/samples/*
      stacked_generator|stackedDialogGenerator:
        enabled: true
        generate_for:
          exclude:
            - test
            - .dart_tool
          include:
            - test/dialogs/integration_test/samples/*
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  # Generate the router file and routes
  stackedRouterGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedRouterGenerator"]
    build_extensions: { ".dart": [".router.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the stacked locator service registrations
  stackedLocatorGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedLocatorGenerator"]
    build_extensions: { ".dart": [".locator.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the form view
  stackedFormGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedFormGenerator"]
    build_extensions: { ".dart": [".form.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the logger
  stackedLoggerGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedLoggerGenerator"]
    build_extensions: { ".dart": [".logger.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the dialogs
  stackedDialogGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedDialogGenerator"]
    build_extensions: { ".dart": [".dialogs.dart"] }
    auto_apply: dependents
    build_to: source

  # Generator the bottomsheets
  stackedBottomsheetGenerator:
    import: "package:stacked_generator/builder.dart"
    builder_factories: ["stackedBottomsheetGenerator"]
    build_extensions: { ".dart": [".bottomsheets.dart"] }
    auto_apply: dependents
    build_to: source
